# Generated by Django 4.2.7 on 2023-12-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='abcd', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
