# Generated by Django 4.2.7 on 2023-12-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_place1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place1',
        ),
    ]
