# Generated by Django 4.2.7 on 2023-12-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_delete_place1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Cakes',
        ),
    ]
