# Generated by Django 4.2.7 on 2023-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
